apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: spring-academy
spec:
  portal:
    registration:
      type: anonymous
    updates:
      workshop: true
    sessions:
      maximum: 15
  workshops:
    # The following are the items that should be added to the trainingportal in the deployment environment.
    - name: spr-boot-native-first-lab
      expires: 60m
      orphaned: 5m
      reserved: 0
    - name: spr-boot-native-migrating-existing-app
      expires: 60m
      orphaned: 5m
      reserved: 0
